### ISSUE TITLE
Arial and Helvetica are both Helvetica

### ISSUE THREAD

**Issue by Squire4Hire** [vladocar/Font-Pairing-Glyph-Comparison-Tool#2]
Selecting Arial over Helvetica displays a perfect match. Arial should be noticeably different than Helvetica which suggests it's returning the wrong typeface.

**Comment by vladocar** [comment]
Probably are both Arial. That is only on Windows if you don't have Helvetica installed. On Mac Helvetica is a system font. On my windows workers because I have Helvetica installed.
